### ISSUE TITLE
Error when converting svg to exp

### ISSUE THREAD

**Issue by FFY00** [backface/stitchcode#1]
```
Warning: SVG import is experimental!Traceback (most recent call last):
  File "/home/anubis/.local/bin/stitchconv.py", line 109, in <module>
    emb.load(infile)
  File "/home/anubis/.local/lib/python2.7/site-packages/stitchcode.py", line 379, in load
    self.import_svg(filename)
  File "/home/anubis/.local/lib/python2.7/site-packages/stitchcode.py", line 1304, in import_svg
    x = int(p.split(' ')[0])
ValueError: invalid literal for int() with base 10: '128.00106,0'

```

**Comment by backface** [comment]
What kind of file did you try to open? 
Currently the  SVG import is really just a quick hack that only reads in files that are also created by this tool/library...
